name: Monitor de Ofertas 30min

on:
  schedule:
    # Roda a cada 30 minutos
    - cron: '*/30 * * * *'
  # Permite rodar manualmente para testar
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar Monitoramento
        env:
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
          TG_SESSION: ${{ secrets.TG_SESSION }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          MEU_CHAT_ID: ${{ secrets.MEU_CHAT_ID }}
        run: python bot_agendado.py